# library name
lib.name = jl

# input source files
gbend~.class.sources = externals/gbend~.cpp dependencies/jl.cpp.lib/dsp/sampler/Gbend.cpp
stut~.class.sources = externals/stut~.cpp dependencies/jl.cpp.lib/dsp/effects/Stut.cpp

# all extra files to be included in binary distribution of the library
datafiles =

# update path to reflect your environment
# PDLIBDIR="/Users/larralde/Documents/Pd/externals"
PDLIBDIR=".."

# include Makefile.pdlibbuilder from submodule directory 'pd-lib-builder'
# update path to reflect your environment
PDLIBBUILDER_DIR=dependencies/pd-lib-builder/
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder
